spring.application.name=BuildRestAPI
spring.output.ansi.enabled=ALWAYS


# Server
#server.port=8080
#Database Configration Mysql : mysql
spring.datasource.url=jdbc:mysql://localhost:3306/StudentDB
spring.datasource.username=root
spring.datasource.password=Harsh@9595
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# PostgreSQL Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/StudentDB
#spring.datasource.username=postgres
#spring.datasource.password=java

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# PostgreSQL Dialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path=/api
springdoc.swagger-ui.path=/docs

spring.security.user.name=akshay
spring.security.user.password=pass

jwt.secretary=gyetrtfxhvgfdgshjkieyrubdhjftsfedtfdshgnjvfksfnvuitfftsydfegcsfehjfuryfghsbvhdjlasjdh